name: primitive
description: some integer and float with limited bits
version: 1.0.1
repository: https://github.com/snowmerak/primitive
homepage: https://snowmerak.pages.dev

environment:
  sdk: '>=2.15.0 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
